
server:
  port: 8762
eureka:
  client:
    service-url: localhost:8761/eureka/
  instance:
    hostname: ${vcap.application.uris[0]}
spring:
  cloud:
    config:
      server:
        git:
          basedir:
          uri:
          